INSERT INTO Students (
Student_id,
    First_name,
    Last_name,
    Date_of_birth,
	Student_year_level,
	Student_email
)
VALUES
    (
        1164700,
        'Lily',
		'Bark',
        '2006-02-21',
		12,
        'ac1164700avcol.school.nz'
    );
	INSERT INTO Students (
Student_id,
    First_name,
    Last_name,
    Date_of_birth,
	Student_year_level,
	Student_email
)
VALUES
    (
        1164701,
        'Monica',
		'Gellar',
        '2007-04-15',
		12,
        'ac1164701avcol.school.nz'
    );
INSERT INTO Students (
Student_id,
    First_name,
    Last_name,
    Date_of_birth,
	Student_year_level,
	Student_email
)
VALUES
    (
        1164702,
        'Chloe',
		'Wood',
        '2007-03-03',
		12,
        'ac1164702avcol.school.nz'
    );  
	INSERT INTO Students (
Student_id,
    First_name,
    Last_name,
    Date_of_birth,
	Student_year_level,
	Student_email
)
VALUES
    (
        1164703,
        'kallisto',
		'Melissa',
        '2007-03-03',
		12,
        'ac1164702avcol.school.nz'
    );  
	INSERT INTO Students (
Student_id,
    First_name,
    Last_name,
    Date_of_birth,
	Student_year_level,
	Student_email
)
VALUES
    (
        1164703,
        '',
		'',
        '2007-03-03',
		12,
        'ac1164702avcol.school.nz'
    );  